// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// SocialProviderWechat is a SocialProvider of type wechat.
	SocialProviderWechat SocialProvider = "wechat"
	// SocialProviderDouyin is a SocialProvider of type douyin.
	SocialProviderDouyin SocialProvider = "douyin"
	// SocialProviderAlipay is a SocialProvider of type alipay.
	SocialProviderAlipay SocialProvider = "alipay"
	// SocialProviderApple is a SocialProvider of type apple.
	SocialProviderApple SocialProvider = "apple"
	// SocialProviderGoogle is a SocialProvider of type google.
	SocialProviderGoogle SocialProvider = "google"
)

var ErrInvalidSocialProvider = errors.New("not a valid SocialProvider")

// String implements the Stringer interface.
func (x SocialProvider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SocialProvider) IsValid() bool {
	_, err := ParseSocialProvider(string(x))
	return err == nil
}

var _SocialProviderValue = map[string]SocialProvider{
	"wechat": SocialProviderWechat,
	"douyin": SocialProviderDouyin,
	"alipay": SocialProviderAlipay,
	"apple":  SocialProviderApple,
	"google": SocialProviderGoogle,
}

// ParseSocialProvider attempts to convert a string to a SocialProvider.
func ParseSocialProvider(name string) (SocialProvider, error) {
	if x, ok := _SocialProviderValue[name]; ok {
		return x, nil
	}
	return SocialProvider(""), fmt.Errorf("%s is %w", name, ErrInvalidSocialProvider)
}

var errSocialProviderNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *SocialProvider) Scan(value interface{}) (err error) {
	if value == nil {
		*x = SocialProvider("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseSocialProvider(v)
	case []byte:
		*x, err = ParseSocialProvider(string(v))
	case SocialProvider:
		*x = v
	case *SocialProvider:
		if v == nil {
			return errSocialProviderNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errSocialProviderNilPtr
		}
		*x, err = ParseSocialProvider(*v)
	default:
		return errors.New("invalid type for SocialProvider")
	}

	return
}

// Value implements the driver Valuer interface.
func (x SocialProvider) Value() (driver.Value, error) {
	return x.String(), nil
}
