// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package model

import (
	"database/sql/driver"
	"errors"
	"fmt"
)

const (
	// CustomerStatusActive is a CustomerStatus of type active.
	CustomerStatusActive CustomerStatus = "active"
	// CustomerStatusInactive is a CustomerStatus of type inactive.
	CustomerStatusInactive CustomerStatus = "inactive"
	// CustomerStatusSuspended is a CustomerStatus of type suspended.
	CustomerStatusSuspended CustomerStatus = "suspended"
	// CustomerStatusBanned is a CustomerStatus of type banned.
	CustomerStatusBanned CustomerStatus = "banned"
	// CustomerStatusDeletionRequested is a CustomerStatus of type deletion_requested.
	CustomerStatusDeletionRequested CustomerStatus = "deletion_requested"
)

var ErrInvalidCustomerStatus = errors.New("not a valid CustomerStatus")

// String implements the Stringer interface.
func (x CustomerStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CustomerStatus) IsValid() bool {
	_, err := ParseCustomerStatus(string(x))
	return err == nil
}

var _CustomerStatusValue = map[string]CustomerStatus{
	"active":             CustomerStatusActive,
	"inactive":           CustomerStatusInactive,
	"suspended":          CustomerStatusSuspended,
	"banned":             CustomerStatusBanned,
	"deletion_requested": CustomerStatusDeletionRequested,
}

// ParseCustomerStatus attempts to convert a string to a CustomerStatus.
func ParseCustomerStatus(name string) (CustomerStatus, error) {
	if x, ok := _CustomerStatusValue[name]; ok {
		return x, nil
	}
	return CustomerStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidCustomerStatus)
}

var errCustomerStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *CustomerStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = CustomerStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseCustomerStatus(v)
	case []byte:
		*x, err = ParseCustomerStatus(string(v))
	case CustomerStatus:
		*x = v
	case *CustomerStatus:
		if v == nil {
			return errCustomerStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errCustomerStatusNilPtr
		}
		*x, err = ParseCustomerStatus(*v)
	default:
		return errors.New("invalid type for CustomerStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x CustomerStatus) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// GenderMale is a Gender of type male.
	GenderMale Gender = "male"
	// GenderFemale is a Gender of type female.
	GenderFemale Gender = "female"
	// GenderOther is a Gender of type other.
	GenderOther Gender = "other"
	// GenderUndisclosed is a Gender of type undisclosed.
	GenderUndisclosed Gender = "undisclosed"
)

var ErrInvalidGender = errors.New("not a valid Gender")

// String implements the Stringer interface.
func (x Gender) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Gender) IsValid() bool {
	_, err := ParseGender(string(x))
	return err == nil
}

var _GenderValue = map[string]Gender{
	"male":        GenderMale,
	"female":      GenderFemale,
	"other":       GenderOther,
	"undisclosed": GenderUndisclosed,
}

// ParseGender attempts to convert a string to a Gender.
func ParseGender(name string) (Gender, error) {
	if x, ok := _GenderValue[name]; ok {
		return x, nil
	}
	return Gender(""), fmt.Errorf("%s is %w", name, ErrInvalidGender)
}

var errGenderNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Gender) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Gender("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseGender(v)
	case []byte:
		*x, err = ParseGender(string(v))
	case Gender:
		*x = v
	case *Gender:
		if v == nil {
			return errGenderNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errGenderNilPtr
		}
		*x, err = ParseGender(*v)
	default:
		return errors.New("invalid type for Gender")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Gender) Value() (driver.Value, error) {
	return x.String(), nil
}
