// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package gormq

import (
	"errors"
	"fmt"
)

const (
	// CrudOpAnd is a ComposeOperator of type and.
	CrudOpAnd ComposeOperator = "and"
	// CrudOpOr is a ComposeOperator of type or.
	CrudOpOr ComposeOperator = "or"
)

var ErrInvalidComposeOperator = errors.New("not a valid ComposeOperator")

// String implements the Stringer interface.
func (x ComposeOperator) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ComposeOperator) IsValid() bool {
	_, err := ParseComposeOperator(string(x))
	return err == nil
}

var _ComposeOperatorValue = map[string]ComposeOperator{
	"and": CrudOpAnd,
	"or":  CrudOpOr,
}

// ParseComposeOperator attempts to convert a string to a ComposeOperator.
func ParseComposeOperator(name string) (ComposeOperator, error) {
	if x, ok := _ComposeOperatorValue[name]; ok {
		return x, nil
	}
	return ComposeOperator(""), fmt.Errorf("%s is %w", name, ErrInvalidComposeOperator)
}

const (
	// CrudOpEq is a FieldOperator of type eq.
	CrudOpEq FieldOperator = "eq"
	// CrudOpNe is a FieldOperator of type ne.
	CrudOpNe FieldOperator = "ne"
	// CrudOpLt is a FieldOperator of type lt.
	CrudOpLt FieldOperator = "lt"
	// CrudOpGt is a FieldOperator of type gt.
	CrudOpGt FieldOperator = "gt"
	// CrudOpLte is a FieldOperator of type lte.
	CrudOpLte FieldOperator = "lte"
	// CrudOpGte is a FieldOperator of type gte.
	CrudOpGte FieldOperator = "gte"
	// CrudOpIn is a FieldOperator of type in.
	CrudOpIn FieldOperator = "in"
	// CrudOpNin is a FieldOperator of type nin.
	CrudOpNin FieldOperator = "nin"
	// CrudOpIna is a FieldOperator of type ina.
	CrudOpIna FieldOperator = "ina"
	// CrudOpNina is a FieldOperator of type nina.
	CrudOpNina FieldOperator = "nina"
	// CrudOpContains is a FieldOperator of type contains.
	CrudOpContains FieldOperator = "contains"
	// CrudOpNcontains is a FieldOperator of type ncontains.
	CrudOpNcontains FieldOperator = "ncontains"
	// CrudOpContainss is a FieldOperator of type containss.
	CrudOpContainss FieldOperator = "containss"
	// CrudOpNcontainss is a FieldOperator of type ncontainss.
	CrudOpNcontainss FieldOperator = "ncontainss"
	// CrudOpBetween is a FieldOperator of type between.
	CrudOpBetween FieldOperator = "between"
	// CrudOpNbetween is a FieldOperator of type nbetween.
	CrudOpNbetween FieldOperator = "nbetween"
	// CrudOpNull is a FieldOperator of type null.
	CrudOpNull FieldOperator = "null"
	// CrudOpNnull is a FieldOperator of type nnull.
	CrudOpNnull FieldOperator = "nnull"
	// CrudOpStartswith is a FieldOperator of type startswith.
	CrudOpStartswith FieldOperator = "startswith"
	// CrudOpNstartswith is a FieldOperator of type nstartswith.
	CrudOpNstartswith FieldOperator = "nstartswith"
	// CrudOpStartswiths is a FieldOperator of type startswiths.
	CrudOpStartswiths FieldOperator = "startswiths"
	// CrudOpNstartswiths is a FieldOperator of type nstartswiths.
	CrudOpNstartswiths FieldOperator = "nstartswiths"
	// CrudOpEndswith is a FieldOperator of type endswith.
	CrudOpEndswith FieldOperator = "endswith"
	// CrudOpNendswith is a FieldOperator of type nendswith.
	CrudOpNendswith FieldOperator = "nendswith"
	// CrudOpEndswiths is a FieldOperator of type endswiths.
	CrudOpEndswiths FieldOperator = "endswiths"
	// CrudOpNendswiths is a FieldOperator of type nendswiths.
	CrudOpNendswiths FieldOperator = "nendswiths"
	// CrudOpTsmatch is a FieldOperator of type tsmatch.
	CrudOpTsmatch FieldOperator = "tsmatch"
)

var ErrInvalidFieldOperator = errors.New("not a valid FieldOperator")

// String implements the Stringer interface.
func (x FieldOperator) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FieldOperator) IsValid() bool {
	_, err := ParseFieldOperator(string(x))
	return err == nil
}

var _FieldOperatorValue = map[string]FieldOperator{
	"eq":           CrudOpEq,
	"ne":           CrudOpNe,
	"lt":           CrudOpLt,
	"gt":           CrudOpGt,
	"lte":          CrudOpLte,
	"gte":          CrudOpGte,
	"in":           CrudOpIn,
	"nin":          CrudOpNin,
	"ina":          CrudOpIna,
	"nina":         CrudOpNina,
	"contains":     CrudOpContains,
	"ncontains":    CrudOpNcontains,
	"containss":    CrudOpContainss,
	"ncontainss":   CrudOpNcontainss,
	"between":      CrudOpBetween,
	"nbetween":     CrudOpNbetween,
	"null":         CrudOpNull,
	"nnull":        CrudOpNnull,
	"startswith":   CrudOpStartswith,
	"nstartswith":  CrudOpNstartswith,
	"startswiths":  CrudOpStartswiths,
	"nstartswiths": CrudOpNstartswiths,
	"endswith":     CrudOpEndswith,
	"nendswith":    CrudOpNendswith,
	"endswiths":    CrudOpEndswiths,
	"nendswiths":   CrudOpNendswiths,
	"tsmatch":      CrudOpTsmatch,
}

// ParseFieldOperator attempts to convert a string to a FieldOperator.
func ParseFieldOperator(name string) (FieldOperator, error) {
	if x, ok := _FieldOperatorValue[name]; ok {
		return x, nil
	}
	return FieldOperator(""), fmt.Errorf("%s is %w", name, ErrInvalidFieldOperator)
}
