package gormq

const suffixNe = "_ne"
const suffixLt = "_lt"
const suffixGt = "_gt"
const suffixLte = "_lte"
const suffixGte = "_gte"
const suffixIn = "_in"
const suffixNin = "_nin"
const suffixIna = "_ina"
const suffixNina = "_nina"
const suffixContains = "_contains"
const suffixNcontains = "_ncontains"
const suffixContainss = "_containss"
const suffixNcontainss = "_ncontainss"
const suffixBetween = "_between"
const suffixNbetween = "_nbetween"
const suffixNull = "_null"
const suffixNnull = "_nnull"
const suffixStartswith = "_startswith"
const suffixNstartswith = "_nstartswith"
const suffixStartswiths = "_startswiths"
const suffixNstartswiths = "_nstartswiths"
const suffixEndswith = "_endswith"
const suffixNendswith = "_nendswith"
const suffixEndswiths = "_endswiths"
const suffixNendswiths = "_nendswiths"
const suffixTsMatch = "_tsmatch"
