// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package rbac

import (
	"errors"
	"fmt"
)

const (
	// ActionCreate is a Action of type create.
	ActionCreate Action = "create"
	// ActionRead is a Action of type read.
	ActionRead Action = "read"
	// ActionUpdate is a Action of type update.
	ActionUpdate Action = "update"
	// ActionDelete is a Action of type delete.
	ActionDelete Action = "delete"
)

var ErrInvalidAction = errors.New("not a valid Action")

// String implements the Stringer interface.
func (x Action) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Action) IsValid() bool {
	_, err := ParseAction(string(x))
	return err == nil
}

var _ActionValue = map[string]Action{
	"create": ActionCreate,
	"read":   ActionRead,
	"update": ActionUpdate,
	"delete": ActionDelete,
}

// ParseAction attempts to convert a string to a Action.
func ParseAction(name string) (Action, error) {
	if x, ok := _ActionValue[name]; ok {
		return x, nil
	}
	return Action(""), fmt.Errorf("%s is %w", name, ErrInvalidAction)
}
