// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package block

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fantacode/ecomm/internal/app/ui/components/button"
	"fantacode/ecomm/internal/app/ui/components/icon"
)

type LangSwitcherProps struct {
	Class string
}

func LangSwitcher(props ...LangSwitcherProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var p LangSwitcherProps
		if len(props) > 0 {
			p = props[0]
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"relative inline-block\" _=\"on click from elsewhere add .hidden to <div[data-lang-menu]/> in me\n\t\t\ton keyup[key is 'Escape'] from elsewhere add .hidden to <div[data-lang-menu]/> in me\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = icon.Languages(icon.Props{Class: "size-5"}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = button.Button(button.Props{
			Size:    button.SizeIcon,
			Variant: button.VariantGhost,
			Class:   p.Class,
			Attributes: templ.Attributes{
				"aria-haspopup": "menu",
				"_":             "on click halt the event then toggle .hidden on the next <div/>",
			},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div data-lang-menu class=\"hidden absolute right-0 mt-2 min-w-32 rounded-md bg-popover p-1 shadow-md border border-border\" role=\"menu\"><button type=\"button\" class=\"w-full text-left flex items-center justify-between px-2 py-1.5 text-sm rounded-sm focus:bg-accent focus:text-accent-foreground hover:bg-accent hover:text-accent-foreground cursor-default\" role=\"menuitem\" _=\"on click\n\t\t\t\t\tset cookies['LANGUAGE'] to {value: 'zh', path: '/', maxAge: 31536000, sameSite: 'Lax'}\n\t\t\t\t\treload() the location of the window\">中文 - 简体</button> <button type=\"button\" class=\"w-full text-left flex items-center justify-between px-2 py-1.5 text-sm rounded-sm focus:bg-accent focus:text-accent-foreground hover:bg-accent hover:text-accent-foreground cursor-default\" role=\"menuitem\" _=\"on click\n\t\t\t\t\tset cookies['LANGUAGE'] to {value: 'zh-Hant', path: '/', maxAge: 31536000, sameSite: 'Lax'}\n\t\t\t\t\treload() the location of the window\">中文 - 繁體</button> <button type=\"button\" class=\"w-full text-left flex items-center justify-between px-2 py-1.5 text-sm rounded-sm focus:bg-accent focus:text-accent-foreground hover:bg-accent hover:text-accent-foreground cursor-default\" role=\"menuitem\" _=\"on click\n\t\t\t\t\tset cookies['LANGUAGE'] to {value: 'en', path: '/', maxAge: 31536000, sameSite: 'Lax'}\n\t\t\t\t\treload() the location of the window\">English</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
