// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package rbac

import (
	"errors"
	"fmt"
)

const (
	// ResourceSystem is a Resource of type system.
	ResourceSystem Resource = "system"
	// ResourceCustomer is a Resource of type customer.
	ResourceCustomer Resource = "customer"
	// ResourceProduct is a Resource of type product.
	ResourceProduct Resource = "product"
)

var ErrInvalidResource = errors.New("not a valid Resource")

// String implements the Stringer interface.
func (x Resource) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Resource) IsValid() bool {
	_, err := ParseResource(string(x))
	return err == nil
}

var _ResourceValue = map[string]Resource{
	"system":   ResourceSystem,
	"customer": ResourceCustomer,
	"product":  ResourceProduct,
}

// ParseResource attempts to convert a string to a Resource.
func ParseResource(name string) (Resource, error) {
	if x, ok := _ResourceValue[name]; ok {
		return x, nil
	}
	return Resource(""), fmt.Errorf("%s is %w", name, ErrInvalidResource)
}
